#!/usr/bin/env php
<?php
/**
 * This file that aim to deal with
 * console commands, just to make all the process easier.
 */

require __DIR__.'/autoload.php';

use \Symfony\Component\Console\Application;

$application = new Application();

$application->add(new \App\Core\Commands\ServerCommand());

$application->run();
